package ru.geekbrains.kozirfm.weatherapp;

public interface Constants {

    String SHARED_PREFERENCES_NAME = "SETTINGS";
    String IS_DARK_THEME_KEY ="IS_DARK_THEME";
    String IS_METRIC_SETTINGS = "IS_METRIC_SETTINGS";
    String MAIN_CITY = "MAIN_CITY";
    String MAIN_TEMPERATURE = "MAIN_TEMPERATURE";
    String MAIN_WIND_POWER = "MAIN_WIND_POWER";
    String MAIN_PRESSURE = "MAIN_PRESSURE";
    String MAIN_DESCRIPTION = "MAIN_DESCRIPTION";
    String MAIN_DISPLAY_FRAGMENT = "MAIN_DISPLAY_FRAGMENT";
    String SELECT_CITY_FRAGMENT = "SELECT_CITY_FRAGMENT";
    String SETTINGS_FRAGMENT = "SETTINGS_FRAGMENT";
    String CURRENT_CITY = "CURRENT_CITY";
    String METRICS_TEMPERATURE_ID = "METRICS_TEMPERATURE_ID";
    String METRICS_TEMPERATURE_VALUE = "METRICS_TEMPERATURE_VALUE";
    String METRICS_PRESSURE_ID = "METRICS_PRESSURE_ID";
    String METRICS_PRESSURE_VALUE = "METRICS_PRESSURE_VALUE";
    String METRICS_WIND_POWER_ID = "METRICS_WIND_POWER_ID";
    String METRICS_WIND_POWER_VALUE = "METRICS_WIND_POWER_VALUE";
}
